name: continuous-integration
on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - name: Test Report
      uses: ellraiser/love.test-report@v1
      with:
        name: Test Output
        path: output/*.xml
